language: php
php:
  - '7.2'
  - '7.3'
  - '7.4'
  - '8.0'
#  - nightly
sudo: required
install:
  - composer install -n
script:
  - XDEBUG_MODE=coverage php vendor/bin/codecept run --coverage-xml
after_success:
  - bash <(curl -Ls https://coverage.codacy.com/get.sh) report -l PHP -r tests/_output/coverage.xml
