language: php
php:
  - '5.6'
  - '7.0'
  - '7.1'
  - nightly
sudo: required
install:
  - composer install -n
script:
  - php vendor/bin/codecept run --coverage-xml
after_script:
  - php vendor/bin/codacycoverage clover tests/_output/coverage.xml
